apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: "jwt-example"
  namespace: istio-poc
spec:
  selector:
    matchLabels:
      app: httpbin
  jwtRules:
  - issuer: "testing@secure.istio.io"
    jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.12/security/tools/jwt/samples/jwks.json"
  - issuer: "securing@cloudready.club"
    jwksUri: "https://raw.githubusercontent.com/ylasmak/jwks/main/istio-1.12.1/samples/security/samples/jwks.json"  